/**
 *
 * $Id$
 */
package com.eclipsesource.glsp.example.statemachine.smgraph.validation;

/**
 * A sample validator interface for {@link com.eclipsesource.glsp.example.statemachine.smgraph.ActivityNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityNodeValidator {
	boolean validate();

	boolean validateNodeType(String value);
}
